#!/bin/sh

set -e

# TODO: we have to make a command to the core s0-port binary that allows us to resolve the correct version of a port,
# this is because it will be highly error prone to try to do it in this shell script

: "${PORTS:=/usr/s0-ports}"

if [ "$(id -u)" -ne 0 ]; then
    echo "port-flags: must be root" >&2
    exit 1
fi

case "$1" in
    -h|--help)
        cat << EOF
Usage: port-flags [OPTIONS] PORT

List available flags for a port.

Arguments:
  PORT                   Port name to list available flags, optionally with version
                         (e.g., term/tmux, term/tmux@3.4)

Options:
  -h, --help             Show this help message
EOF
        ;;
    *)
        . "$PORTS/$1"
        echo $FLAGS
        ;;
esac


